SELECT
    --key
    h.hourly_weather_id,
    --location
    l.LOCATIONID,
    l.LOCATION,
    l.CITY,
    l.STATE,
    l.COUNTRY,
    l.LAT,
    l.LONG,
    --date and time fields
    h.weather_date,
    h.weather_time,
    h.datetime_epoch,
    --daily weather
    d.TEMPMAX AS DAILY_TEMPMAX,
    d.TEMPMIN AS DAILY_TEMPMIN,
    d.TEMP AS DAILY_TEMP,
    d.FEELSLIKEMAX AS DAILY_FEELSLIKEMAX,
    d.FEELSLIKEMIN AS DAILY_FEELSLIKEMIN,
    d.FEELSLIKE AS DAILY_FEELSLIKE,
    d.DEW AS DAILY_DEW,
    d.HUMIDITY AS DAILY_HUMIDITY,
    d.PRECIP AS DAILY_PRECIP,
    d.PRECIPPROB AS DAILY_PRECIPPROB,
    d.PRECIPCOVER AS DAILY_PRECIPCOVER,
    d.SNOW AS DAILY_SNOW,
    d.SNOWDEPTH AS DAILY_SNOWDEPTH,
    d.WINDGUST AS DAILY_WINDGUST,
    d.WINDSPEED AS DAILY_WINDSPEED,
    d.WINDDIR AS DAILY_WINDDIR,
    d.PRESSURE AS DAILY_PRESSURE,
    d.CLOUDCOVER AS DAILY_CLOUDCOVER,
    d.VISIBILITY AS DAILY_VISIBILITY,
    d.SOLARRADIATION AS DAILY_SOLARRADIATION,
    d.SOLARENERGY AS DAILY_SOLARENERGY,
    d.UVINDEX AS DAILY_UVINDEX,
    d.SUNRISE AS DAILY_SUNRISE,
    d.SUNSET AS DAILY_SUNSET,
    d.MOONPHASE AS DAILY_MOONPHASE,
    d.CONDITIONS AS DAILY_CONDITIONS,
    d.DESCRIPTION AS DAILY_DESCRIPTION,
    d.ICON AS DAILY_ICON,
    --hourly weather
    h.TEMP AS HOURLY_TEMP,
    h.FEELSLIKE AS HOURLY_FEELSLIKE,
    h.DEW AS HOURLY_DEW,
    h.HUMIDITY AS HOURLY_HUMIDITY,
    h.PRECIP AS HOURLY_PRECIP,
    h.PRECIPPROB AS HOURLY_PRECIPPROB,
    h.PRESSURE AS HOURLY_PRESSURE,
    h.SNOW AS HOURLY_SNOW,
    h.SNOWDEPTH AS HOURLY_SNOWDEPTH,
    h.SOLARRADIATION AS HOURLY_SOLARRADIATION,
    h.SOLARENERGY AS HOURLY_SOLARENERGY,
    h.UVINDEX AS HOURLY_UVINDEX,
    h.VISIBILITY AS HOURLY_VISIBILITY,
    h.WINDDIR AS HOURLY_WINDDIR,
    h.WINDGUST AS HOURLY_WINDGUST,
    h.WINDSPEED AS HOURLY_WIND_SPEED,
    h.CONDITIONS AS HOURLY_CONDITIONS,
    h.ICON AS HOURLY_ICON
FROM {{ ref('INT_HOURLY_WEATHER') }} h
LEFT JOIN {{ ref('INT_DAILY_WEATHER') }} d
    ON h.LOCATIONID = d.LOCATIONID
    AND h.weather_date = d.weather_date
LEFT JOIN {{ ref('DIM_LOCATION') }} l
    ON h.LOCATIONID = l.LOCATIONID